"""Load a palette file and substitute {{ key }} placeholders in templates.

Placeholders use {{ }} rather than $ or ${} because the files being templated
are full of literal dollar signs (hyprlock's $base, shell's ${HOME}) and
braces (CSS), which a naive delimiter would corrupt.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

PLACEHOLDER = re.compile(r"\{\{\s*([A-Za-z0-9_.]+)\s*\}\}")


class UnknownKey(KeyError):
    """A template referenced a key the palette does not define."""



# xterm-256 palette: 16-231 are a 6x6x6 RGB cube, 232-255 a 24-step grey ramp.
_CUBE_LEVELS = (0, 95, 135, 175, 215, 255)


def _nearest_x256(value: str) -> int:
    """Nearest xterm-256 palette index for a #rrggbb colour.

    curses TUIs (ranger, and anything using ncurses colour pairs) take a
    palette index, not a hex string.
    """
    bare = value.lstrip("#")
    r, g, b = (int(bare[i:i + 2], 16) for i in (0, 2, 4))

    def dist(c1, c2):
        return sum((a - b_) ** 2 for a, b_ in zip(c1, c2))

    # best cube entry
    idx = [min(range(6), key=lambda i: abs(_CUBE_LEVELS[i] - c)) for c in (r, g, b)]
    cube_rgb = tuple(_CUBE_LEVELS[i] for i in idx)
    cube_index = 16 + 36 * idx[0] + 6 * idx[1] + idx[2]

    # best grey-ramp entry
    grey_i = min(range(24), key=lambda i: abs((8 + i * 10) - (r + g + b) / 3))
    grey_val = 8 + grey_i * 10
    grey_index = 232 + grey_i

    if dist((r, g, b), (grey_val,) * 3) < dist((r, g, b), cube_rgb):
        return grey_index
    return cube_index


def _flatten(table: dict, prefix: str = "") -> dict[str, str]:
    out: dict[str, str] = {}
    for key, value in table.items():
        dotted = f"{prefix}{key}"
        if isinstance(value, dict):
            out.update(_flatten(value, f"{dotted}."))
        elif isinstance(value, bool):
            # str(True) is "True", which is a nil global in Lua and invalid in
            # TOML/JSON/CSS. Every consumer of this renderer wants lowercase.
            out[dotted] = "true" if value else "false"
        else:
            out[dotted] = str(value)
    return out


def _expand_colours(values: dict[str, str]) -> dict[str, str]:
    """Add _bare and _rgb variants for every #rrggbb value.

    Hyprland wants rgba(ff4d9dee), GTK wants rgb(255, 77, 157), and most
    config files want #FF4D9D. Precomputing the variants keeps templates
    free of logic.
    """
    extra: dict[str, str] = {}
    for key, value in values.items():
        if not (isinstance(value, str) and re.fullmatch(r"#[0-9A-Fa-f]{6}", value)):
            continue
        bare = value[1:].lower()
        extra[f"{key}_bare"] = bare
        r, g, b = (int(bare[i:i + 2], 16) for i in (0, 2, 4))
        extra[f"{key}_rgb"] = f"{r}, {g}, {b}"
        extra[f"{key}_x256"] = str(_nearest_x256(value))
    return extra


def _expand_name(values: dict[str, str]) -> dict[str, str]:
    """Add a title-cased display variant of the palette name.

    The palette's own `name` key is a slug ("nebula-bloom") used for file
    and directory names. Metadata fields (a vicinae theme's display name,
    "GENERATED by" comment headers) read better in title case, so derive
    "Nebula Bloom" from it here rather than hardcoding it in every template.
    """
    name = values.get("name")
    if not isinstance(name, str) or not name:
        return {}
    return {
        "name_title": " ".join(word.capitalize() for word in name.split("-")),
        # ranger colourschemes are Python modules, so the name must be a
        # legal identifier: "nebula-bloom" -> "nebula_bloom".
        "name_snake": name.replace("-", "_"),
    }


def load_palette(path: Path | str) -> dict[str, str]:
    with open(path, "rb") as handle:
        values = _flatten(tomllib.load(handle))
    values.update(_expand_colours(values))
    values.update(_expand_name(values))
    return values


def render(text: str, values: dict[str, str]) -> str:
    missing: list[str] = []

    def substitute(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            missing.append(key)
            return match.group(0)
        return values[key]

    out = PLACEHOLDER.sub(substitute, text)
    if missing:
        raise UnknownKey(f"palette has no key(s): {', '.join(sorted(set(missing)))}")
    return out
