-- GENERATED by theme/apply.py — do not edit.
-- Edit theme/palettes/nebula-bloom.toml instead.
--
-- Pure data: this file returns a table and calls no Hyprland API, so it
-- cannot break the compositor config beyond the values it supplies.
return {
	gaps_in = 8,
	gaps_out = 16,
	border_size = 2,

	active_border_1 = "rgba(ff4d9dee)",
	active_border_2 = "rgba(ff9e6bee)",
	inactive_border = "rgba(45243baa)",

	rounding = 16,
	dim_inactive = true,
	dim_strength = 0.12,
	active_opacity = 0.96,
	inactive_opacity = 0.92,

	blur_size = 8,
	blur_passes = 2,
	blur_vibrancy = 0.17,

	shadow_color = 0xee0d0409,
}
