# GENERATED by theme/apply.py — do not edit.
# Edit theme/palettes/nebula-bloom.toml instead.
#
# ranger colourscheme for Nebula Bloom. ranger is a curses app, so colours
# are xterm-256 palette indices rather than hex; the generator derives each
# index from the palette's hex value.

from __future__ import (absolute_import, division, print_function)

from ranger.gui.colorscheme import ColorScheme
from ranger.gui.color import (
    default_colors, normal, bold, reverse, dim,
)

BASE      = 233
SURFACE0  = 234
SURFACE1  = 235
SURFACE2  = 237
MUTED     = 139
SUBTEXT   = 181
TEXT      = 255
MAGENTA   = 205
PEACH     = 215
VIOLET    = 133
LILAC     = 182
BLUE      = 104
CYAN      = 81
GREEN     = 115
YELLOW    = 222
RED       = 203


class NebulaBloom(ColorScheme):
    progress_bar_color = MAGENTA

    def use(self, context):  # noqa: C901  (ranger's own API shape)
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        if context.in_browser:
            if context.selected:
                attr = reverse
            else:
                attr = normal

            if context.empty or context.error:
                fg = RED
            if context.border:
                fg = SURFACE2
            if context.media:
                fg = VIOLET
                if context.image:
                    fg = LILAC
                elif context.video:
                    fg = MAGENTA
                elif context.audio:
                    fg = PEACH
            if context.container:
                fg = RED
            if context.directory:
                attr |= bold
                fg = BLUE
            elif context.executable and not any((
                    context.media, context.container,
                    context.fifo, context.socket)):
                attr |= bold
                fg = GREEN
            if context.socket:
                fg = PEACH
                attr |= bold
            if context.fifo or context.device:
                fg = YELLOW
                if context.device:
                    attr |= bold
            if context.link:
                fg = CYAN if context.good else RED
            if context.tag_marker and not context.selected:
                attr |= bold
                fg = MAGENTA if fg in (RED, MAGENTA) else YELLOW
            if not context.selected and (context.cut or context.copied):
                attr |= bold
                fg = BASE
                bg = SURFACE1
            if context.main_column:
                if context.selected:
                    attr |= bold
                if context.marked:
                    attr |= bold
                    fg = YELLOW
            if context.badinfo:
                if attr & reverse:
                    bg = MAGENTA
                else:
                    fg = MAGENTA
            if context.inactive_pane:
                fg = MUTED

        elif context.in_titlebar:
            attr |= bold
            if context.hostname:
                fg = RED if context.bad else MAGENTA
            elif context.directory:
                fg = CYAN
            elif context.tab:
                if context.good:
                    fg = BASE
                    bg = MAGENTA
                else:
                    fg = MUTED
            elif context.link:
                fg = CYAN

        elif context.in_statusbar:
            if context.permissions:
                if context.good:
                    fg = SUBTEXT
                elif context.bad:
                    fg = RED
            if context.marked:
                attr |= bold | reverse
                fg = YELLOW
            if context.frozen:
                attr |= bold | reverse
                fg = CYAN
            if context.message:
                if context.bad:
                    attr |= bold
                    fg = RED
            if context.loaded:
                bg = self.progress_bar_color
            if context.vcsinfo:
                fg = BLUE
                attr &= ~bold
            if context.vcscommit:
                fg = YELLOW
                attr &= ~bold
            if context.vcsdate:
                fg = CYAN
                attr &= ~bold

        if context.text:
            if context.highlight:
                attr |= reverse

        if context.in_taskview:
            if context.title:
                fg = MAGENTA
            if context.selected:
                attr |= reverse
            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        if context.vcsfile and not context.selected:
            attr &= ~bold
            if context.vcsconflict:
                fg = VIOLET
            elif context.vcsuntracked:
                fg = CYAN
            elif context.vcschanged:
                fg = RED
            elif context.vcsunknown:
                fg = RED
            elif context.vcsstaged:
                fg = GREEN
            elif context.vcssync:
                fg = GREEN
            elif context.vcsignored:
                fg = MUTED

        elif context.vcsremote and not context.selected:
            attr &= ~bold
            if context.vcssync or context.vcsnone:
                fg = GREEN
            elif context.vcsbehind:
                fg = RED
            elif context.vcsahead:
                fg = BLUE
            elif context.vcsdiverged:
                fg = VIOLET
            elif context.vcsunknown:
                fg = RED

        return fg, bg, attr
